### ISSUE TITLE
redis集群部署发生错误，我的apiserver使用的6443端口

### ISSUE THREAD

**Issue by lsjrepo** [marscqy/redis-in-k8s#3]
PersistentVolumeClaim is not bound: "rediscluster-sts-redis-cluster-0" (repeated 2 times)

下面是我的配置文件:
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dep-redis-ctrl
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: dep-redis-ctrl
        environment: test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: cntr-redis-cc
        image: dev.dingxiang-inc.com:4567/ctu-group/docker-images/redis:4.0.2
        imagePullPolicy: IfNotPresent
        env:
        - name: CLUSTER_CTRL
          value: "true"
        - name: REDIS_CLUSTER_SLAVE_QUANTUM
          value: "1"
        - name: LOG_LEVEL
          value: "0"
        - name: SHOW_HEALTH_DETAIL
          value: "true"
        - name: API_SERVER_ADDR
          value: "192.168.100.136:6443"
        - name: REDIS_PORT
          value: "6380"
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 6380
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: sts-redis-cluster
spec:
  serviceName: "svc-redis-cluster"
  replicas: 6
  template:
    metadata:
      labels:
        name: sts-redis-cluster
        environment: test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: cntr-redis-cluster
        image: dev.dingxiang-inc.com:4567/ctu-group/docker-images/redis:4.0.2
        imagePullPolicy: IfNotPresent
        env:
        - name: CLUSTER
          value: "true"
        - name: REDIS_PORT
          value: "6380"
        - name: API_SERVER_ADDR
          value: "192.168.100.136:6443"
        - name: LOG_LEVEL
          value: "0"
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 6380
        volumeMounts:
        - name: rediscluster
          mountPath: /data/redis
        securityContext:
          capabilities: {}
          privileged: true
  volumeClaimTemplates:
  - metadata:
      name: rediscluster
      annotations:
        volume.beta.kubernetes.io/storage-class: "fast"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: svc-redis-cluster
  labels:
    name: svc-redis-cluster
spec:
  ports:
  - port: 6379
    targetPort: 6379
  clusterIP: None
  selector:
    name: sts-redis-cluster
---
apiVersion: v1
kind: Service
metadata:
  name: svc-redis-cluster-np
  labels:
    name: svc-redis-cluster-np
spec:
  ports:
  - port: 30000
    targetPort: 30000
    nodePort: 30000
  type: NodePort
  selector:
    name: sts-redis-cluster
---
apiVersion: v1
kind: Service
metadata:
  name: svc-redis-cc
  labels:
    name: svc-redis-cc
spec:
  ports:
  - port: 6379
    targetPort: 6379
  clusterIP: None
  selector:
    name: sts-redis-cc

**Comment by cqyisbug** [comment]
1.针对报错建议去看下PVC 和 PV 这些概念,如果想暂时规避这个问题请将persistent_flag 设置为false
2.6443 端口应该走的是HTTPS,使用https在pod里面需要一个证书,并且还可能需要建service account 这些资源,建议了解下k8s的权限.
