### ISSUE TITLE
以前测试过，k8s-flannel网络不能安装Redis cluster

### ISSUE THREAD

**Issue by prodanlabs** [marscqy/redis-in-k8s#4]
Calico可以安装Redis cluster。

**Comment by prodanlabs** [comment]
我自己构建的镜像包，跟你的差不多，然后创建6个pod，进入其中一个pod执行
redis-trib.rb create --replicas 1 ip:port,ip:port,ip:port,ip:port,ip:port,ip:port ，按照提示输入yes后，就卡在了 waiting for the cluster to join ........的页面

后来我把k8s的网络换成了Calico，就可以了

我不知道你的k8s是不是也用flannel网络，但是我看了redis-cluster.yaml文件，是创建了7个Redis pod，StatefulSet创建的6个是Redis集群节点，Deployment创建一个pod是干嘛用的呢

**Comment by cqyisbug** [comment]
Deployment创建一个pod ,这个pod比较特殊,是用来控制管理整个redis集群的.  flannel 安装的时候我之前遇到的问题是集群之间的pod ip互相找不到. 这个问题已经解决了.  或者你可以试着改下flannel的ipmasq  设置,查下这个配置,和这个配置有关系
