### ISSUE TITLE
解决pod ip改变的问题

### ISSUE THREAD

**Issue by hubigsea** [marscqy/redis-in-k8s#5]
是通过hostnetwork 这个参数来固定pod的ip吗

**Comment by cqyisbug** [comment]
hostnetwork是让docker 用 宿主机的网络,实际效果是,hostnetwork开启之后,docker的ip就是宿主机的ip,所以一个宿主机上只能部署一个类型的docker.
如果需要固定ip的话,则需要标签来进行一些改造.
